version: '3.8'

services:
  tlinkwebportal:
    image: ghcr.io/brianhumlicek/tlinkwebportal:latest
    container_name: tlinkwebportal
    ports:
      - "5181:8080"
      - "3072:3072"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - EnableHttps=false
    volumes:
      - ./userSettings.json:/app/userSettings.json
    restart: unless-stopped